// This file has been generated by Specta. Do not edit this file manually.
export type AbortRevertRequest = {
  repositoryPath: string;
};

export type AbortRevertResponse = {
  aborted: boolean;
};

export type AppError = {
  category: AppErrorCategory;
  summary: string;
  context: OperationContext;
  git: GitCommandError | null;
};

export type AppErrorCategory = "expected" | "unexpected" | "fatal";

export type AppEvent =
  | ({
      type: "repoChanged";
    } & RepoChangedEvent)
  | ({
      type: "operationProgress";
    } & OperationProgressEvent)
  | ({
      type: "fetchState";
    } & FetchStateEvent)
  | ({
      type: "conflictEntered";
    } & ConflictEnteredEvent)
  | ({
      type: "stashRestoreState";
    } & StashRestoreStateEvent);

export type AppInfo = {
  productName: string;
  executableName: string;
  identifier: string;
};

export type AppSettings = {
  schemaVersion?: number;
  language?: LanguagePreference;
  appearance?: AppearanceSettings;
  git?: GitSettings;
  updates?: UpdateSettings;
  privacy?: PrivacySettings;
  onboarding?: OnboardingSettings;
  window?: GlobalWindowSettings;
  paths?: PathSettings;
  logging?: LoggingSettings;
  recentProjectLimit?: number;
};

export type AppearanceSettings = {
  theme?: ThemePreference;
};

export type AutoTrackingRule = {
  sourceBranch: string;
  targetBranch: string;
};

export type BranchExistence = "localOnly" | "remoteOnly" | "localAndRemote";

export type BranchListResponse = {
  branches: BranchSummary[];
};

export type BranchNameValidationRequest = {
  repositoryPath: string;
  name: string;
};

export type BranchNameValidationResponse = {
  name: string;
  valid: boolean;
  exists: boolean;
  message: string | null;
};

export type BranchOperationResponse =
  | { status: "completed"; repositoryPath: string; branchName: string }
  | {
      status: "conflicts";
      repositoryPath: string;
      branchName: string;
      conflict: ConflictEnteredEvent;
      stashRecovery: StashRecoveryPoint | null;
    };

export type BranchSummary = {
  name: string;
  shortName: string;
  existence: BranchExistence;
  current: boolean;
  headOid: string | null;
  upstream: string | null;
  ahead: number;
  behind: number;
  latestCommitUnixSeconds: string | null;
};

export type CancelCloneRepositoryRequest = {
  operationId: OperationId;
};

export type CancelCloneRepositoryResponse = {
  cancelled: boolean;
};

export type CancelStashRestoreRequest = {
  repositoryPath: string;
  recovery: StashRecoveryPoint;
};

export type CancelStashRestoreResponse = {
  restored: boolean;
  droppedRecoveryStash: boolean;
};

export type CheckoutBranchRequest = {
  repositoryPath: string;
  branchName: string;
  localChangesMode: CheckoutLocalChangesMode;
  operationId: OperationId | null;
};

export type CheckoutLocalChangesMode = "requireClean" | "autoStash" | "discard";

export type CloneRepositoryRequest = {
  url: string;
  targetParentDirectory: string;
  directoryName: string;
  toolIdentity: ToolGitIdentity | null;
  operationId: OperationId | null;
};

export type CloneRepositoryResponse = {
  repository: OpenRepositoryResponse;
};

export type CommitRequest = {
  repositoryPath: string;
  paths: string[];
  message: string;
  largeFileThresholdMb: number | null;
  largeFileDecision: LargeFileDecision;
  disableRepositoryGpgsign: boolean;
};

export type CommitResponse =
  | {
      status: "committed";
      oid: string;
      committedPaths: string[];
      lfsTrackedPaths: string[];
    }
  | {
      status: "largeFilesNeedDecision";
      largeFiles: LargeFileWarning[];
      thresholdMb: number;
    }
  | { status: "gpgSignFailed"; summary: string; stderr: string }
  | { status: "nothingToCommit" };

export type CommitSummary = {
  oid: string;
  parents: string[];
  authorName: string;
  authorEmail: string;
  authoredAtUnixSeconds: string;
  subject: string;
  refs: string[];
};

export type ConfigChangeEvent =
  | { type: "settingsUpdated"; settings: AppSettings }
  | { type: "projectUpdated"; projectKey: string; project: ProjectSettings }
  | {
      type: "projectRemoved";
      projectKey: string;
      project: ProjectSettings | null;
    };

export type ConflictCancelRequest = {
  repositoryPath: string;
  operationId: OperationId;
};

export type ConflictCancelResponse = {
  aborted: ConflictOperationKind;
};

export type ConflictCompleteRequest = {
  repositoryPath: string;
  operationId: OperationId;
  paths: string[];
};

export type ConflictCompleteResponse = {
  continuation: ConflictOperationKind;
};

export type ConflictDetailResponse = {
  file: ConflictFile;
  detail: ConflictFileDetail;
};

export type ConflictEnteredEvent = {
  operationId: OperationId;
  repositoryPath: string;
  operationName: string;
  files: ConflictFile[];
};

export type ConflictFile = {
  path: string;
  status: ConflictResolutionStatus;
  fileKind: DiffFileKind;
};

export type ConflictFileDetail =
  | {
      kind: "text";
      currentText: string;
      ownText: string;
      otherText: string;
      hunks: ConflictHunk[];
      language: string | null;
    }
  | {
      kind: "binary";
      own: ConflictSideFile | null;
      other: ConflictSideFile | null;
    };

export type ConflictHunk = {
  id: number;
  startLine: number;
  endLine: number;
  startOffset: number;
  endOffset: number;
  ownText: string;
  otherText: string;
};

export type ConflictImagePreview = {
  dataUrl: string;
};

export type ConflictListRequest = {
  repositoryPath: string;
};

export type ConflictListResponse = {
  operation: ConflictOperation | null;
  files: ConflictFile[];
};

export type ConflictOperation = {
  kind: ConflictOperationKind;
  label: string;
};

export type ConflictOperationKind =
  "merge" | "rebase" | "cherryPick" | "revert";

export type ConflictPathRequest = {
  repositoryPath: string;
  path: string;
};

export type ConflictResolutionStatus = "unresolved" | "resolved";

export type ConflictSaveResolutionRequest = {
  repositoryPath: string;
  path: string;
  content: string;
  pendingHunks: number;
};

export type ConflictSaveResolutionResponse = {
  file: ConflictFile;
};

export type ConflictSelectSideRequest = {
  repositoryPath: string;
  paths: string[];
  side: ConflictSide;
};

export type ConflictSelectSideResponse = {
  files: ConflictFile[];
};

export type ConflictSide = "own" | "other";

export type ConflictSideFile = {
  side: ConflictSide;
  oid: string | null;
  sizeBytes: number | null;
  modifiedUnixSeconds: string | null;
  mimeType: string | null;
  preview: ConflictImagePreview | null;
};

export type CreateAutoStashRequest = {
  repositoryPath: string;
  reason: string;
  includeUntracked: boolean;
  paths: string[];
};

export type CreateBranchRequest = {
  repositoryPath: string;
  name: string;
  baseBranch: string;
  checkoutImmediately: boolean;
  createRemote: boolean;
  localChangesMode: CheckoutLocalChangesMode;
  operationId: OperationId | null;
};

export type CreateStashRequest = {
  repositoryPath: string;
  message: string;
  includeUntracked: boolean;
  paths: string[];
};

export type CreateStashResponse = {
  created: boolean;
  stash: StashEntry | null;
  stdout: string;
};

export type DeleteBranchRequest = {
  repositoryPath: string;
  branchName: string;
  deleteRemote: boolean;
  forceRemoteOnly: boolean;
};

export type DeleteHttpsCredentialRequest = {
  protocol: string;
  host: string;
  path: string | null;
  scope: HttpsCredentialScope;
};

export type DeleteStashRequest = {
  repositoryPath: string;
  selector: string;
};

export type DeleteStashResponse = {
  deletedSelector: string;
  stdout: string;
};

export type DiffChangeKind =
  "added" | "modified" | "deleted" | "renamed" | "copied";

export type DiffFileKind =
  "text" | "binary" | "image" | "lfsPointer" | "oversizedText";

export type DiffPayload = {
  oldPath: string | null;
  newPath: string;
  changeKind: DiffChangeKind;
  fileKind: DiffFileKind;
  lfsLock: LfsLockStatus | null;
  metadata: { [key in string]: string };
};

export type FetchRepositoryRequest = {
  repositoryPath: string;
};

export type FetchRepositoryResponse = {
  event: FetchStateEvent;
  skipped: boolean;
};

export type FetchState = "idle" | "fetching" | "offline" | "failed";

export type FetchStateEvent = {
  repositoryPath: string;
  state: FetchState;
  lastSuccessAt: string | null;
  message: string | null;
};

export type GenerateSshKeyRequest = {
  comment: string | null;
  passphrase: string | null;
};

export type GitCommandError = {
  command: string[];
  exitCode: number | null;
  stdout: string;
  stderr: string;
};

export type GitDistManifest = {
  schemaVersion: number;
  platform: string;
  gitVersion: string;
  gitLfsVersion: string;
  windowsOpenSshVersion: string | null;
  helperVersion: string;
  paths: GitDistPaths;
  sha256: { [key in string]: string };
};

export type GitDistPaths = {
  gitExecutable: string;
  gitLfsExecutable: string;
  windowsSshExecutable: string | null;
  credentialHelper: string;
  sshAskpass: string;
};

export type GitSettings = {
  autoFetch?: boolean;
  fetchIntervalSeconds?: number;
  user?: GitUserSettings;
  rememberSshPassphrase?: boolean;
};

export type GitUserSettings = {
  name?: string | null;
  email?: string | null;
};

export type GitignoreFileResponse = {
  repositoryPath: string;
  path: string;
  content: string;
  exists: boolean;
};

export type GitignoreRequest = {
  repositoryPath: string;
};

export type GlobalWindowSettings = {
  defaultGeometry?: WindowGeometry;
};

export type HealthResponse = {
  app: AppInfo;
  status: string;
};

export type HttpsCredentialEntry = {
  protocol: string;
  host: string;
  path: string | null;
  username: string;
  scope: HttpsCredentialScope;
};

export type HttpsCredentialListResponse = {
  credentials: HttpsCredentialEntry[];
};

export type HttpsCredentialPromptReason = "missing" | "invalidOrExpired";

export type HttpsCredentialPromptRequest = {
  protocol: string;
  host: string;
  path: string | null;
  reason: HttpsCredentialPromptReason;
  suggestedUsername: string | null;
  defaultScope: HttpsCredentialScope;
};

export type HttpsCredentialScope = "host" | "path";

export type IdentityField = "name" | "email";

export type IdentitySource = "repository" | "globalGitconfig" | "missing";

export type IdentitySourcesResponse = {
  settings: GitUserSettings;
  globalGitconfig: GitUserSettings;
  globalGitconfigPath: string | null;
};

export type IdentityValidationRequest = {
  repositoryPath: string | null;
  operationName: string;
  requiresIdentity?: boolean;
};

export type IdentityValidationResponse = {
  operationName: string;
  requiresIdentity: boolean;
  identity: ResolvedGitIdentity;
};

export type IndexLockInfo = {
  path: string;
  ageSeconds: number;
  warning: string;
};

export type LanguagePreference = "system" | "zhCn" | "enUs";

export type LargeFileCheckSettings = {
  enabled?: boolean;
  thresholdMb?: number;
};

export type LargeFileDecision = "prompt" | "trackWithLfs" | "commitNormally";

export type LargeFileWarning = {
  path: string;
  sizeBytes: string;
};

export type LfsLockStatus = {
  locked: boolean;
  owner: string | null;
};

export type LocalChange = {
  path: string;
  oldPath: string | null;
  changeKind: DiffChangeKind;
  indexStatus: string;
  worktreeStatus: string;
};

export type LocalChangesResponse = {
  changes: LocalChange[];
};

export type LocalChangesViewMode = "flat" | "tree";

export type LogLevelPreference = "error" | "warn" | "info" | "debug" | "trace";

export type LogPageRequest = {
  repositoryPath: string;
  after: string | null;
  limit: number | null;
};

export type LogPageResponse = {
  commits: CommitSummary[];
  nextAfter: string | null;
};

export type LogSearchRequest = {
  repositoryPath: string;
  grep: string | null;
  author: string | null;
  pickaxe: string | null;
  after: string | null;
  limit: number | null;
};

export type LoggingSettings = {
  level?: LogLevelPreference;
  retainDays?: number;
};

export type OnboardingSettings = {
  onboarded?: boolean;
};

export type OpenLogDirResponse = {
  path: string;
  opened: boolean;
};

export type OpenRepositoryRequest = {
  path: string;
  toolIdentity: ToolGitIdentity | null;
};

export type OpenRepositoryResponse = {
  repositoryPath: string;
  gitDir: string;
  remoteMode: RepositoryRemoteMode;
  remotes: RepositoryRemote[];
  warnings: RepositoryOpenWarning[];
  health: RepositoryHealth;
  summary: RepositorySummary;
};

export type OperationContext = {
  operationId: OperationId | null;
  windowLabel: string | null;
  repositoryPath: string | null;
  operationName: string;
};

export type OperationId = string;

export type OperationProgressEvent = {
  operationId: OperationId;
  label: string;
  progress: ProgressState;
  cancellable: boolean;
};

export type PathSettings = {
  lastCloneParentDir?: string | null;
};

export type PrivacySettings = {
  gravatarEnabled?: boolean;
};

export type ProgressState =
  { kind: "indeterminate" } | { kind: "percent"; value: number | null };

export type ProjectSettings = {
  path?: string;
  displayName?: string | null;
  pinned?: boolean;
  lastOpenedAt?: string | null;
  lastBranch?: string | null;
  autoTrackingRules?: AutoTrackingRule[];
  sidebar?: SidebarLayoutSettings;
  localChangesViewMode?: LocalChangesViewMode;
  windowGeometry?: WindowGeometry | null;
  reviewModeCrash?: ReviewModeCrashMarker | null;
  largeFileCheck?: LargeFileCheckSettings;
};

export type ProjectSettingsRequest = {
  repositoryPath: string;
};

export type ProjectsDocument = {
  schemaVersion?: number;
  projects?: { [key in string]: ProjectSettings };
};

export type RemoteSettingsResponse = {
  repositoryPath: string;
  remoteMode: RepositoryRemoteMode;
  originUrl: string | null;
};

export type RepoChangedEvent = {
  repositoryPath: string;
  changedQueries: RepoQueryKind[];
};

export type RepoQueryKind =
  "summary" | "branches" | "stashes" | "localChanges" | "history";

export type RepositoryHeadState =
  | { kind: "branch"; name: string; oid: string | null }
  | { kind: "detached"; oid: string }
  | { kind: "unborn"; branch: string };

export type RepositoryHealth = {
  head: RepositoryHeadState;
  middleStates: RepositoryMiddleState[];
  indexLock: IndexLockInfo | null;
};

export type RepositoryMiddleState = {
  kind: RepositoryMiddleStateKind;
  path: string;
  abortCommand: string[] | null;
};

export type RepositoryMiddleStateKind =
  "merge" | "rebase" | "cherryPick" | "revert" | "bisect";

export type RepositoryOpenWarning = {
  kind: RepositoryOpenWarningKind;
  message: string;
};

export type RepositoryOpenWarningKind =
  | "multipleRemotesOriginManaged"
  | "multipleRemotesNoOrigin"
  | "noRemote"
  | "detachedHead"
  | "unbornHead"
  | "operationInProgress"
  | "indexLockPresent";

export type RepositoryPathRequest = {
  repositoryPath: string;
};

export type RepositoryRemote = {
  name: string;
  url: string;
  isOrigin: boolean;
  managed: boolean;
};

export type RepositoryRemoteMode = "origin" | "noRemote";

export type RepositorySummary = {
  repositoryPath: string;
  currentBranch: string | null;
  headOid: string | null;
  remoteMode: RepositoryRemoteMode;
  hasOrigin: boolean;
  isDetached: boolean;
  isUnborn: boolean;
  inProgress: boolean;
};

export type ResolvedGitIdentity = {
  name: string | null;
  email: string | null;
  source: IdentitySource;
  complete: boolean;
  emailValid: boolean;
  missing: IdentityField[];
};

export type RestoreChangesRequest = {
  repositoryPath: string;
  paths: string[];
};

export type RestoreChangesResponse = {
  restoredPaths: string[];
  backupRoot: string | null;
  backedUpPaths: string[];
};

export type RestoreStashRequest = {
  repositoryPath: string;
  selector: string;
  dropOnSuccess: boolean;
  operationName: string | null;
};

export type RestoreStashResponse = {
  selector: string;
  oid: string;
  recovery: StashRecoveryPoint;
  outcome: StashRestoreOutcome;
};

export type RevertCommitRequest = {
  repositoryPath: string;
  oid: string;
};

export type RevertCommitResponse =
  | { status: "reverted"; oid: string; message: string }
  | { status: "disabled"; reason: RevertDisabledReason }
  | { status: "conflicted"; operationId: OperationId; files: ConflictFile[] };

export type RevertDisabledReason =
  | "mergeCommit"
  | "notOnCurrentBranch"
  | "detachedHead"
  | "unbornHead"
  | "operationInProgress";

export type ReviewModeCrashMarker = {
  autoStashRef?: string | null;
  enteredAt?: string | null;
  operationId?: string | null;
};

export type SaveAppSettingsRequest = {
  settings: AppSettings;
  openRepositoryPaths?: string[];
  validateIdentity?: boolean;
};

export type SaveGitignoreRequest = {
  repositoryPath: string;
  content: string;
};

export type SaveProjectSettingsRequest = {
  repositoryPath: string;
  largeFileCheck: LargeFileCheckSettings;
};

export type SaveRemoteSettingsRequest = {
  repositoryPath: string;
  originUrl: string | null;
  removeOrigin?: boolean;
};

export type SettingsSnapshot = {
  appVersion: string;
  settings: AppSettings;
  identitySources: IdentitySourcesResponse;
  sshKey: SshKeyStatus;
};

export type SidebarLayoutSettings = {
  widthPx?: number;
  branchSectionRatioPercent?: number;
  branchesCollapsed?: boolean;
  stashesCollapsed?: boolean;
};

export type SshKeyStatus = {
  privateKeyPath: string | null;
  publicKeyPath: string | null;
  publicKey: string | null;
  exists: boolean;
};

export type StashDetailsRequest = {
  repositoryPath: string;
  selector: string;
};

export type StashDetailsResponse = {
  entry: StashEntry;
  files: StashDiffFile[];
  rawDiff: string;
};

export type StashDiffFile = {
  path: string;
  oldPath: string | null;
  changeKind: DiffChangeKind;
  fileKind: DiffFileKind;
  patch: string;
};

export type StashEntry = {
  index: number;
  selector: string;
  oid: string;
  message: string;
  branch: string | null;
  createdAtUnixSeconds: string | null;
  isAutoStash: boolean;
  origin: string | null;
};

export type StashListResponse = {
  stashes: StashEntry[];
};

export type StashRecoveryPoint = {
  id: string;
  headOid: string | null;
  stashOid: string | null;
  stashSelector: string | null;
};

export type StashRestoreOutcome =
  | { status: "applied"; dropped: boolean }
  | { status: "conflicts"; conflict: ConflictEnteredEvent };

export type StashRestoreStateEvent = {
  repositoryPath: string;
  selector: string;
  recovery: StashRecoveryPoint;
  status: StashRestoreStatus;
};

export type StashRestoreStatus =
  "applying" | "applied" | "conflicted" | "cancelled";

export type ThemePreference = "system" | "light" | "dark";

export type ToolGitIdentity = {
  name: string | null;
  email: string | null;
};

export type UpdateSettings = {
  autoCheck?: boolean;
};

export type WindowGeometry = {
  width?: number;
  height?: number;
  x?: number | null;
  y?: number | null;
  maximized?: boolean;
};
