// This file has been generated by Specta. Do not edit this file manually.
export type AppError = {
	category: AppErrorCategory,
	summary: string,
	context: OperationContext,
	git: GitCommandError | null,
};

export type AppErrorCategory = "expected" | "unexpected" | "fatal";

export type AppEvent = {
	type: "repoChanged",
} & RepoChangedEvent | {
	type: "operationProgress",
} & OperationProgressEvent | {
	type: "fetchState",
} & FetchStateEvent | {
	type: "conflictEntered",
} & ConflictEnteredEvent;

export type AppInfo = {
	productName: string,
	executableName: string,
	identifier: string,
};

export type AppSettings = {
	schemaVersion?: number,
	language?: LanguagePreference,
	appearance?: AppearanceSettings,
	git?: GitSettings,
	updates?: UpdateSettings,
	privacy?: PrivacySettings,
	onboarding?: OnboardingSettings,
	window?: GlobalWindowSettings,
	paths?: PathSettings,
	logging?: LoggingSettings,
	recentProjectLimit?: number,
};

export type AppearanceSettings = {
	theme?: ThemePreference,
};

export type AutoTrackingRule = {
	sourceBranch: string,
	targetBranch: string,
};

export type ConfigChangeEvent = { type: "settingsUpdated"; settings: AppSettings } | { type: "projectUpdated"; projectKey: string; project: ProjectSettings } | { type: "projectRemoved"; projectKey: string; project: ProjectSettings | null };

export type ConflictEnteredEvent = {
	operationId: OperationId,
	repositoryPath: string,
	operationName: string,
	files: ConflictFile[],
};

export type ConflictFile = {
	path: string,
	status: ConflictResolutionStatus,
	fileKind: DiffFileKind,
};

export type ConflictResolutionStatus = "unresolved" | "resolved";

export type DiffChangeKind = "added" | "modified" | "deleted" | "renamed" | "copied";

export type DiffFileKind = "text" | "binary" | "image" | "lfsPointer" | "oversizedText";

export type DiffPayload = {
	oldPath: string | null,
	newPath: string,
	changeKind: DiffChangeKind,
	fileKind: DiffFileKind,
	lfsLock: LfsLockStatus | null,
	metadata: { [key in string]: string },
};

export type FetchState = "idle" | "fetching" | "offline" | "failed";

export type FetchStateEvent = {
	repositoryPath: string,
	state: FetchState,
	lastSuccessAt: string | null,
	message: string | null,
};

export type GitCommandError = {
	command: string[],
	exitCode: number | null,
	stdout: string,
	stderr: string,
};

export type GitDistManifest = {
	schemaVersion: number,
	platform: string,
	gitVersion: string,
	gitLfsVersion: string,
	windowsOpenSshVersion: string | null,
	helperVersion: string,
	paths: GitDistPaths,
	sha256: { [key in string]: string },
};

export type GitDistPaths = {
	gitExecutable: string,
	gitLfsExecutable: string,
	windowsSshExecutable: string | null,
	credentialHelper: string,
	sshAskpass: string,
};

export type GitSettings = {
	autoFetch?: boolean,
	fetchIntervalSeconds?: number,
	user?: GitUserSettings,
	rememberSshPassphrase?: boolean,
};

export type GitUserSettings = {
	name?: string | null,
	email?: string | null,
};

export type GlobalWindowSettings = {
	defaultGeometry?: WindowGeometry,
};

export type HealthResponse = {
	app: AppInfo,
	status: string,
};

export type LanguagePreference = "system" | "zhCn" | "enUs";

export type LargeFileCheckSettings = {
	enabled?: boolean,
	thresholdMb?: number,
};

export type LfsLockStatus = {
	locked: boolean,
	owner: string | null,
};

export type LocalChangesViewMode = "flat" | "tree";

export type LogLevelPreference = "error" | "warn" | "info" | "debug" | "trace";

export type LoggingSettings = {
	level?: LogLevelPreference,
	retainDays?: number,
};

export type OnboardingSettings = {
	onboarded?: boolean,
};

export type OpenLogDirResponse = {
	path: string,
	opened: boolean,
};

export type OperationContext = {
	operationId: OperationId | null,
	windowLabel: string | null,
	repositoryPath: string | null,
	operationName: string,
};

export type OperationId = string;

export type OperationProgressEvent = {
	operationId: OperationId,
	label: string,
	progress: ProgressState,
	cancellable: boolean,
};

export type PathSettings = {
	lastCloneParentDir?: string | null,
};

export type PrivacySettings = {
	gravatarEnabled?: boolean,
};

export type ProgressState = { kind: "indeterminate" } | { kind: "percent"; value: number | null };

export type ProjectSettings = {
	path?: string,
	displayName?: string | null,
	pinned?: boolean,
	lastOpenedAt?: string | null,
	lastBranch?: string | null,
	autoTrackingRules?: AutoTrackingRule[],
	sidebar?: SidebarLayoutSettings,
	localChangesViewMode?: LocalChangesViewMode,
	windowGeometry?: WindowGeometry | null,
	reviewModeCrash?: ReviewModeCrashMarker | null,
	largeFileCheck?: LargeFileCheckSettings,
};

export type ProjectsDocument = {
	schemaVersion?: number,
	projects?: { [key in string]: ProjectSettings },
};

export type RepoChangedEvent = {
	repositoryPath: string,
	changedQueries: RepoQueryKind[],
};

export type RepoQueryKind = "summary" | "branches" | "stashes" | "localChanges" | "history";

export type ReviewModeCrashMarker = {
	autoStashRef?: string | null,
	enteredAt?: string | null,
	operationId?: string | null,
};

export type SidebarLayoutSettings = {
	widthPx?: number,
	branchSectionRatioPercent?: number,
	branchesCollapsed?: boolean,
	stashesCollapsed?: boolean,
};

export type ThemePreference = "system" | "light" | "dark";

export type UpdateSettings = {
	autoCheck?: boolean,
};

export type WindowGeometry = {
	width?: number,
	height?: number,
	x?: number | null,
	y?: number | null,
	maximized?: boolean,
};
